# Generated by Django 4.2.4 on 2023-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bigreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bigreview_content", models.CharField(max_length=140)),
                ("is_blocked", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
