# Generated by Django 4.2.4 on 2023-08-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bigreviews", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigreview",
            name="bigreview_review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bigreviews",
                to="reviews.review",
            ),
        ),
    ]
