# Generated by Django 4.2.4 on 2023-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoxMusical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("musical_id", models.CharField(max_length=20)),
                ("musical_name", models.CharField(max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("ranking", models.PositiveIntegerField()),
                ("place", models.CharField(max_length=20)),
                ("poster", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="BoxTheater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theater_id", models.CharField(max_length=20)),
                ("theater_name", models.CharField(max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("ranking", models.PositiveIntegerField()),
                ("place", models.CharField(max_length=20)),
                ("poster", models.URLField()),
            ],
        ),
    ]
