# Generated by Django 4.2.4 on 2023-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Youtube_Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=80)),
                ("content", models.TextField()),
                ("video_url", models.URLField()),
                ("thumbnail_url", models.URLField()),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("is_blocked", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
