# Generated by Django 4.2.4 on 2023-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("Image", models.URLField(blank=True, null=True)),
                ("title", models.CharField(max_length=30)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("free", "자게"), ("after", "후기"), ("trade", "양도")],
                        max_length=12,
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("is_blocked", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
