# Generated by Django 4.2.4 on 2023-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("board", "게시글"),
                            ("review", "댓글"),
                            ("big_review", "대댓글"),
                        ],
                        max_length=11,
                    ),
                ),
                ("reason", models.TextField()),
                ("target_user", models.CharField(max_length=30)),
                (
                    "target_title",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("target_content", models.TextField()),
                ("target_pk", models.PositiveIntegerField()),
            ],
        ),
    ]
